class AcademicAIError(Exception): pass
class ConfigurationError(AcademicAIError): pass
class ProviderError(AcademicAIError): pass
class LLMError(ProviderError): pass
class EmbeddingError(ProviderError): pass
class VectorStoreError(ProviderError): pass
class DocumentError(AcademicAIError): pass
class DiscoveryError(AcademicAIError): pass
class LanguageError(AcademicAIError): pass
class QueryError(AcademicAIError): pass
class RetrievalError(AcademicAIError): pass
class AssessmentError(AcademicAIError): pass
class ProfileError(AcademicAIError): pass
class PersonalizationError(AcademicAIError): pass
class ContentGenerationError(AcademicAIError): pass
class RoutingError(AcademicAIError): pass
class StorageError(AcademicAIError): pass
class OrchestrationError(AcademicAIError): pass